# Generated by Django 5.1.5 on 2025-01-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_addressuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='product',
        ),
    ]
