# Generated by Django 5.1.5 on 2025-01-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_product_validate_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='announcement.extra'),
        ),
    ]
