# Generated by Django 5.1.5 on 2025-01-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_alter_product_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra',
        ),
        migrations.AddField(
            model_name='product',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_mine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('uzs', 'UZS'), ('rub', 'RUB'), ('usd', 'USD')], default='uzs', max_length=3),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
