# Generated by Django 5.1.5 on 2025-01-22 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_validate_address_alter_user_phone_number'),
        ('common', '0002_remove_addressuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validate_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.addressuser'),
        ),
    ]
