# Generated by Django 5.1.5 on 2025-01-29 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 7, 0, 34, 581257, tzinfo=datetime.timezone.utc)),
        ),
    ]
